Server
witkiewiczmikolaj/helbreder pull request #14
Opened 2022-10-10 06:15 UTC by witkiewiczmikolaj

2022-10-10 07:51 UTC, wiktorkisielewski requested changes

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +import paramiko
`ModuleNotFoundError: No module named 'paramiko'`
it must be added to the `requirements.txt`, so it is available in docker image we are running

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +        cpu_load_sum += float(top[83 + (12 * i)])
what are these numbers: `83`, `12 * i`?

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    client.connect(f'{ip}', username='root', pkey=k)
it is wrong to assume the `ssh` key is always granted access as a `root` user - in most cases, it won't :(
Add a way to define a server username in a request sent to helbreder API and use it as a parameter here

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +        response = "Server rebooted! " + server_reboot(os.environ.get('RSA_KEY'), os.environ.get('RSA_PASSWORD'), t_name)
Here you are giving the information that the server was rebooted before even attempting to reboot it :p
There might be cases when it failed (the server has an unkillable process, ssh authentication fails, etc..)
It should be rebooted first, than confirmed that it was (might take from seconds to minutes) and the information about successful reboot should be sent at the end

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/app.py
> +        return server_response(action, t_kind, t_name)
don't user a `server_response` function to trigger action, it is misleading (it should be the name of variable with response)

Try to make this module function similar to other ones:
```python
#action  = get_stats | target_kind = cpu
func = str(action + '_')
#func = 'get_stats_'
server_response = eval(func)(t_name, t_kind)
#this eval will result in calling the "get_stats_(cpu)" function (which should be defined in server.py) and assigned the returned output from it to the "server_response" variable 
return server_resonse
```

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/doc/possibilities.yml
>      targets:
I guess a `None` option is desired as a target, since it is not added when requesting a reboot

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    if action == 'Get_stats' and t_kind == 'CPU':
use `eval` (code snippet in a comment associated with `app.py`)

Change this to the `get_stats_(target_kind)` function to stick with naming in other modules

Move reboot functionality to new function called `reboot_(target_name/IP)`

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    k = paramiko.RSAKey.from_private_key_file(f'{rsa_key}', f'{rsa_password}')
`rsa_key` suggest it is the key, not the file containing a key, please change it to `rsa_provate_key_file_pathe` or something more clear

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    k = paramiko.RSAKey.from_private_key_file(f'{rsa_key}', f'{rsa_password}')
`29/43/56/69` these lines are basically the same -> create a function for establish ssh connection and use it there instead

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/doc/possibilities.yml
> +      - Reebot1
remove `reboot1` - it does not exist and we don't have to have 3 possible action - 2 is enough

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +def server_info_cpu(rsa_key, rsa_password, ip):
add a way to get info from one core only, while keeping the possibility to get average (like now)

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    top = execute_command(client, 'top -bn2')
`top` is not the best choice imho:
- it is a process (this means you are increasing to CPU usage while getting it)
- it outputs way to much info

why don't use `cat /proc/stat` which is a file that you only read and analyze?

2022-10-10 07:51 UTC, wiktorkisielewski commented on core/app/modules/server.py
> +    mem = execute_command(client, 'df -h /')
why is it `-h /` in this command? 
`-h` makes the server calculate from bytes to MB/GB - not always wanted 
`/` means you are omitting some partitions (this is ok as this is the main and most used one in Linux), but there is no info about it so it is very misleading

2022-10-13 11:07 UTC, wiktorkisielewski requested changes

2022-10-13 11:07 UTC, wiktorkisielewski commented on core/app/templates/languages.py
> +        data['action'] = button_clicked[1]
since now you know the `eval` magic, you might want to use it here to avoid hardcoding data/buttons here

(based on enhanced `possibilities.yml` for example)

2022-10-13 11:07 UTC, wiktorkisielewski commented on core/app/templates/languages.py
> +        data['action'] = button_clicked[1]
just a suggestion tho, it would require lots of restructuring probably so it might be better to do it in separate PR

2022-10-13 11:07 UTC, wiktorkisielewski commented on core/app/templates/post.py
> +button_clicked = ["*module*", "*action*", "*target*", "*username*", "*password*", "*target_name*", "*user*", "*IP*", "*resource_type*"]
same as in `languages.py` -> lets leave it for now, but it could be much more generic (hopefully will be)

2022-10-13 11:27 UTC, witkiewiczmikolaj commented on core/app/modules/server.py
> +        usage = "Resource type exceeds cpu number used by the server, or you passed wrong argument!"
Thanks <3

2022-10-21 06:59 UTC, merged